### ISSUE TITLE
Lift & Shift 전반적으로 다듬기

### ISSUE THREAD

**Issue by ssoxong** [GAE4COON/Cloud_Backend#125]
# Testcase
![diagram (19)](https://github.com/GAE4COON/Cloud_Backend/assets/112956015/ce1f68e6-9588-436a-a3c1-ade0102075a5)

## Current
![image](https://github.com/GAE4COON/Cloud_Backend/assets/112956015/9d18064f-23e7-48ac-b81b-676ffbbf1a9f)

## Wanted
![image](https://github.com/GAE4COON/Cloud_Backend/assets/112956015/c98ee22b-4a81-4fa6-8ab9-8ce65554f2c0)

## Task
- [x] 관문 방화벽은 Network FW 대응
- [x] FW를 통하지 않는 노드 연결 예외처리 
![image](https://github.com/GAE4COON/Cloud_Backend/assets/112956015/f080cd0b-0f2b-4802-bd38-1540df80c663)
- [x] IPS 대응
- [x] #129
- [x] 전체적으로 감싸는 그룹이 없어도 Lift & Shift 동작하도록 처리 필요
- [x] #128
